jobs:
  build-java:
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Clone Repo
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Validate projects
      run: .github/workflows/build/folder-crawler.sh
      shell: bash
    - continue-on-error: true
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      name: Set commit range (push to the main branch, e.g. merge)
      run: echo "COMMIT_RANGE="${{ github.event.before }}.."" >> $GITHUB_ENV
    - continue-on-error: true
      if: github.event_name == 'pull_request'
      name: Set commit range (pull request)
      run: echo "COMMIT_RANGE="HEAD~.."" >> $GITHUB_ENV
    - continue-on-error: true
      env:
        COMMIT_RANGE: ${{ env.COMMIT_RANGE }}
        REGEX: ${{ matrix.regex }}
      name: Build
      run: .github/workflows/build/build.sh
      shell: bash
    strategy:
      fail-fast: false
      matrix:
        regex:
        - java/advanced/APIDemo
        - java/advanced/InlineAdaptiveBannerExample
        - java/advanced/RewardedSSVExample
        - kotlin/advanced/APIDemo
        - kotlin/advanced/InlineAdaptiveBannerExample
        - java/admob/AppOpenExample
        - java/admob/BannerExample
        - java/admob/FullScreenNativeExample
        - java/admob/InterstitialExample
        - java/admob/NativeAdvancedExample
        - java/admob/RewardedInterstitialExample
        - java/admob/RewardedVideoExample
        - kotlin/admob/AppOpenExample
        - kotlin/admob/BannerExample
        - kotlin/admob/InterstitialExample
        - kotlin/admob/NativeAdvancedExample
        - kotlin/admob/RewardedInterstitialExample
        - kotlin/admob/RewardedVideoExample
        - java/admanager/AppOpenExample
        - java/admanager/BannerExample
        - java/admanager/InterstitialExample
        - java/admanager/NativeAdsExample
        - java/admanager/RewardedInterstitialExample
        - java/admanager/RewardedVideoExample
        - kotlin/admanager/AppOpenExample
        - kotlin/admanager/BannerExample
        - kotlin/admanager/InterstitialExample
        - kotlin/admanager/NativeAdsExample
        - kotlin/admanager/RewardedInterstitialExample
        - kotlin/admanager/RewardedVideoExample
name: Build Status
on:
  repository_dispatch:
    types: trigger-ga___build.yml
